#!/bin/bash

export ROOT=/dev/sdb1
export SWAP=/dev/sdb2
export HOME=/dev/sdb3

release=oneiric
target=mnt
mirror=http://de.archive.ubuntu.com/ubuntu/
target_arch=amd64

echo "Mounting images....."
./mountall

echo "Debootstrap starting............."
debootstrap --arch $target_arch $release $target $mirror

echo "Creating new sources.list"
cat > mnt/etc/apt/sources.list << EOF
# deb cdrom:[Ubuntu 11.10 _Oneiric Ocelot_ - Release amd64 (20111012)]/ dists/oneiric/main/binary-i386/

# deb cdrom:[Ubuntu 11.10 _Oneiric Ocelot_ - Release amd64 (20111012)]/ oneiric main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://si.archive.ubuntu.com/ubuntu/ oneiric main restricted
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://si.archive.ubuntu.com/ubuntu/ oneiric-updates main restricted
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://si.archive.ubuntu.com/ubuntu/ oneiric universe
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric universe
deb http://si.archive.ubuntu.com/ubuntu/ oneiric-updates universe
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://si.archive.ubuntu.com/ubuntu/ oneiric multiverse
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric multiverse
deb http://si.archive.ubuntu.com/ubuntu/ oneiric-updates multiverse
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://si.archive.ubuntu.com/ubuntu/ oneiric-backports main restricted universe multiverse
deb-src http://si.archive.ubuntu.com/ubuntu/ oneiric-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu oneiric-security main restricted
deb-src http://security.ubuntu.com/ubuntu oneiric-security main restricted
deb http://security.ubuntu.com/ubuntu oneiric-security universe
deb-src http://security.ubuntu.com/ubuntu oneiric-security universe
deb http://security.ubuntu.com/ubuntu oneiric-security multiverse
deb-src http://security.ubuntu.com/ubuntu oneiric-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu oneiric partner
# deb-src http://archive.canonical.com/ubuntu oneiric partner

## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
deb http://extras.ubuntu.com/ubuntu oneiric main
deb-src http://extras.ubuntu.com/ubuntu oneiric main
EOF

echo "Copying mtab"
cp /etc/mtab mnt/etc/mtab

echo "Check if sources are OK"
read ok

# Enable aliases in shell scripts
shopt -s expand_aliases
alias ch="chroot mnt/"
alias chins="chroot mnt/ apt-get install -y"

echo "Please enter root password"
ch passwd

echo "Updating sources........"
ch apt-get update

echo "Installing packages........."
chins vim nano screen
chins lxc vlan bridge-utils

chins linux-image

echo "Do you want me to write my default network config? yes/no"
read answer
if [ $answer == 'yes' ]; then
    echo "Writing network config........"
    cat >> mnt/etc/network/interfaces <<EOF
# It gets configured by bridge
auto eth0
iface eth0 inet manual

# LXC bridge
auto br0
iface br0 inet dhcp
    bridge_ports eth0
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0
EOF
fi

echo "Do you have flash drive we will write this image on? yes/no"
read answer
if [ $answer == 'yes' ]; then
    ./mkfstab
    ./mkgrub
    ./mountall
fi

echo "Mount home if there is one and then pres any key."
read home

echo "Please select your admin user..."
read username
ch adduser $username
ch usermod -a -G sudo $username

echo "When you will want to change image, mount it using ./mountall,"
echo "when done just write it in to sd card using \"dd if=root.img of=YOUR_DEVICE\"."
